service: trail2

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    events:
      - http:
          path: random-number
          method: get
          cors: true # Add CORS if needed
  home:
    handler: src/handler.home
    events:
      - http:
          path: home
          method: get
          cors: true # Add CORS if needed
  owner:
    handler: src/handler.owner
    events:
      - http:
          path: owner
          method: get
          cors: true # Add CORS if needed

    